-- IOOS Economic Impact Evidence Matrix schema for Supabase.
-- Run this in the Supabase SQL editor for project spfyejzxqornsfmoansk.

create table if not exists public.source_registry (
  source_id text primary key,
  source_name text not null,
  source_url text not null,
  source_type text not null,
  verification_status text not null,
  rows_supported text not null,
  notes text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.evidence_matrix (
  row_id text primary key,
  impact_domain text not null,
  ioos_component text not null,
  region text not null,
  user_group text not null,
  decision_supported text not null,
  economic_pathway text not null,
  metric text not null,
  metric_year_or_dollar_year text not null,
  source_id text not null references public.source_registry(source_id) on update cascade,
  evidence_strength text not null check (evidence_strength in ('Strong', 'Medium', 'Contextual', 'Modeled', 'Needs verification')),
  ioos_attribution_strength text not null check (ioos_attribution_strength in ('Strong', 'Medium', 'Contextual', 'Modeled', 'Needs verification')),
  source_verification_needed text not null check (source_verification_needed in ('Yes', 'No')),
  limitations text not null,
  claim_allowed text not null,
  update_frequency text not null,
  ai_extraction_notes text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.review_needed (
  id bigint generated by default as identity primary key,
  severity text not null,
  row_id text not null,
  source_id text not null,
  check_name text not null,
  message text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.staged_evidence (
  id bigint generated by default as identity primary key,
  row_id text not null,
  impact_domain text not null,
  ioos_component text not null,
  region text not null,
  user_group text not null,
  decision_supported text not null,
  economic_pathway text not null,
  metric text not null,
  metric_year_or_dollar_year text not null,
  source text not null,
  source_url text not null,
  evidence_strength text not null,
  ioos_attribution_strength text not null,
  source_verification_needed text not null,
  limitations text not null,
  claim_allowed text not null,
  update_frequency text not null,
  ai_extraction_notes text not null,
  updated_at timestamptz not null default now()
);

create index if not exists evidence_matrix_source_id_idx on public.evidence_matrix(source_id);
create index if not exists evidence_matrix_impact_domain_idx on public.evidence_matrix(impact_domain);
create index if not exists evidence_matrix_evidence_strength_idx on public.evidence_matrix(evidence_strength);
create index if not exists review_needed_row_id_idx on public.review_needed(row_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_source_registry_updated_at on public.source_registry;
create trigger set_source_registry_updated_at
before update on public.source_registry
for each row execute function public.set_updated_at();

drop trigger if exists set_evidence_matrix_updated_at on public.evidence_matrix;
create trigger set_evidence_matrix_updated_at
before update on public.evidence_matrix
for each row execute function public.set_updated_at();

drop trigger if exists set_review_needed_updated_at on public.review_needed;
create trigger set_review_needed_updated_at
before update on public.review_needed
for each row execute function public.set_updated_at();

drop trigger if exists set_staged_evidence_updated_at on public.staged_evidence;
create trigger set_staged_evidence_updated_at
before update on public.staged_evidence
for each row execute function public.set_updated_at();

create table if not exists public.best_sources (
  source_id text primary key,
  source_name text not null,
  source_url text not null,
  source_type text not null,
  priority_tier text not null check (priority_tier in ('primary', 'supporting', 'context', 'hold')),
  briefing_role text not null,
  impact_domains text not null,
  staged_row_ids text not null,
  key_metrics text not null,
  evidence_profile text not null,
  attribution_profile text not null,
  recommended_claim_language text not null,
  caveats text not null,
  source_verification_needed text not null check (source_verification_needed in ('Yes', 'No')),
  status text not null default 'planned',
  updated_at timestamptz not null default now()
);

create index if not exists best_sources_priority_tier_idx on public.best_sources(priority_tier);
create index if not exists best_sources_status_idx on public.best_sources(status);

drop trigger if exists set_best_sources_updated_at on public.best_sources;
create trigger set_best_sources_updated_at
before update on public.best_sources
for each row execute function public.set_updated_at();
