-- IOOS Economic Impact Evidence Matrix schema for Supabase.
-- Current staging model:
--   1. MARACOOS: pilot-region intake table for MARACOOS candidate rows.
--   2. staged_evidence: shared candidate/evidence rows after review or backfill.
--   3. best_sources: curated source shortlist and briefing guidance.

create table if not exists public.staged_evidence (
  id bigint generated by default as identity primary key,
  row_id text not null,
  date_record_created date not null default current_date,
  impact_domain text not null,
  ioos_component text not null,
  region text not null,
  ioos_region_code text not null default 'Unknown',
  user_group text not null,
  decision_supported text not null,
  economic_pathway text not null,
  metric text not null,
  metric_year_or_dollar_year text not null,
  source text not null,
  source_url text not null,
  source_publication_year text not null default 'Unknown' check (source_publication_year = 'Unknown' or source_publication_year ~ '^(18|19|20)[0-9]{2}$'),
  evidence_strength text not null check (evidence_strength in ('Strong', 'Medium', 'Contextual', 'Modeled', 'Needs verification')),
  ioos_attribution_strength text not null check (ioos_attribution_strength in ('Strong', 'Medium', 'Contextual', 'Modeled', 'Needs verification')),
  economic_number_type text not null default 'No economic number' check (economic_number_type in ('Observed dollar benefit', 'Modeled dollar estimate', 'Dollar exposure/context', 'Operational metric only', 'No economic number', 'Do not use')),
  ioos_role_type text not null default 'Partner/infrastructure source' check (ioos_role_type in ('Direct impact source', 'Direct decision-support source', 'Backend data source', 'Partner/infrastructure source', 'Context only', 'No IOOS attribution')),
  source_verification_needed text not null check (source_verification_needed in ('Yes', 'No')),
  allowed_use text not null default 'Needs manual claim-use classification before briefing use.',
  not_allowed_use text not null default 'Do not present as IOOS-attributable economic return until reviewed.',
  limitations text not null,
  claim_allowed text not null,
  update_frequency text not null,
  ai_extraction_notes text not null,
  prompt_used text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.best_sources (
  source_id text primary key,
  source_name text not null,
  source_url text not null,
  source_type text not null,
  ioos_region_code text not null default 'Unknown',
  priority_tier text not null check (priority_tier in ('primary', 'supporting', 'context', 'hold')),
  briefing_role text not null,
  impact_domains text not null,
  staged_row_ids text not null,
  key_metrics text not null,
  evidence_profile text not null,
  attribution_profile text not null,
  recommended_claim_language text not null,
  caveats text not null,
  source_verification_needed text not null check (source_verification_needed in ('Yes', 'No')),
  status text not null default 'planned',
  updated_at timestamptz not null default now()
);

create index if not exists staged_evidence_impact_domain_idx on public.staged_evidence(impact_domain);
create index if not exists staged_evidence_date_record_created_idx on public.staged_evidence(date_record_created);
create index if not exists staged_evidence_ioos_region_code_idx on public.staged_evidence(ioos_region_code);
create index if not exists staged_evidence_source_publication_year_idx on public.staged_evidence(source_publication_year);
create index if not exists staged_evidence_source_verification_needed_idx on public.staged_evidence(source_verification_needed);
create index if not exists staged_evidence_economic_number_type_idx on public.staged_evidence(economic_number_type);
create index if not exists staged_evidence_ioos_role_type_idx on public.staged_evidence(ioos_role_type);
create index if not exists staged_evidence_evidence_strength_idx on public.staged_evidence(evidence_strength);
create index if not exists best_sources_ioos_region_code_idx on public.best_sources(ioos_region_code);
create index if not exists best_sources_priority_tier_idx on public.best_sources(priority_tier);
create index if not exists best_sources_status_idx on public.best_sources(status);
create index if not exists best_sources_source_verification_needed_idx on public.best_sources(source_verification_needed);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_staged_evidence_updated_at on public.staged_evidence;
create trigger set_staged_evidence_updated_at
before update on public.staged_evidence
for each row execute function public.set_updated_at();

drop trigger if exists set_best_sources_updated_at on public.best_sources;
create trigger set_best_sources_updated_at
before update on public.best_sources
for each row execute function public.set_updated_at();

create table if not exists public."MARACOOS" (
  like public.staged_evidence including all
);

alter table public."MARACOOS"
  add column if not exists id bigint generated by default as identity,
  add column if not exists date_record_created date not null default current_date,
  add column if not exists source_publication_year text not null default 'Unknown',
  add column if not exists economic_number_type text not null default 'No economic number',
  add column if not exists ioos_role_type text not null default 'Partner/infrastructure source',
  add column if not exists allowed_use text not null default 'Needs manual claim-use classification before briefing use.',
  add column if not exists not_allowed_use text not null default 'Do not present as IOOS-attributable economic return until reviewed.',
  add column if not exists prompt_used text not null default '';

drop trigger if exists set_maracoos_updated_at on public."MARACOOS";
create trigger set_maracoos_updated_at
before update on public."MARACOOS"
for each row execute function public.set_updated_at();

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'staging_aoos_evidence',
    'staging_caricoos_evidence',
    'staging_cencoos_evidence',
    'staging_gcoos_evidence',
    'staging_glos_evidence',
    'staging_maracoos_evidence',
    'staging_nanoos_evidence',
    'staging_neracoos_evidence',
    'staging_pacioos_evidence',
    'staging_sccoos_evidence',
    'staging_secoora_evidence'
  ]
  loop
    execute format(
      'create table if not exists public.%I (like public.staged_evidence including all)',
      table_name
    );
    execute format(
      'drop trigger if exists %I on public.%I',
      'set_' || table_name || '_updated_at',
      table_name
    );
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
      'set_' || table_name || '_updated_at',
      table_name
    );
  end loop;
end $$;
