-- MARACOOS pilot intake table.
--
-- The MARACOOS build can stay in its own table while candidate rows are being
-- reviewed. The table intentionally uses the same schema as staged_evidence so
-- accepted rows can be backfilled into the shared staging layer later.

create table if not exists public."MARACOOS" (
  like public.staged_evidence including all
);

alter table public."MARACOOS"
  add column if not exists id bigint generated by default as identity,
  add column if not exists date_record_created date not null default current_date,
  add column if not exists economic_number_type text not null default 'No economic number',
  add column if not exists ioos_role_type text not null default 'Partner/infrastructure source',
  add column if not exists allowed_use text not null default 'Needs manual claim-use classification before briefing use.',
  add column if not exists not_allowed_use text not null default 'Do not present as IOOS-attributable economic return until reviewed.',
  add column if not exists prompt_used text not null default '';
