-- Optional regional staging tables for one-region-at-a-time intake.
--
-- These tables use the same schema as public.staged_evidence so candidate CSV
-- rows can be kept separate by IOOS association before backfilling into the
-- shared staged_evidence table.

create table if not exists public."MARACOOS" (
  like public.staged_evidence including all
);

alter table public."MARACOOS"
  add column if not exists id bigint generated by default as identity,
  add column if not exists date_record_created date not null default current_date,
  add column if not exists source_publication_year text not null default 'Unknown',
  add column if not exists economic_number_type text not null default 'No economic number',
  add column if not exists ioos_role_type text not null default 'Partner/infrastructure source',
  add column if not exists allowed_use text not null default 'Needs manual claim-use classification before briefing use.',
  add column if not exists not_allowed_use text not null default 'Do not present as IOOS-attributable economic return until reviewed.',
  add column if not exists prompt_used text not null default '';

drop trigger if exists set_maracoos_updated_at on public."MARACOOS";
create trigger set_maracoos_updated_at
before update on public."MARACOOS"
for each row execute function public.set_updated_at();

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'staging_aoos_evidence',
    'staging_caricoos_evidence',
    'staging_cencoos_evidence',
    'staging_gcoos_evidence',
    'staging_glos_evidence',
    'staging_maracoos_evidence',
    'staging_nanoos_evidence',
    'staging_neracoos_evidence',
    'staging_pacioos_evidence',
    'staging_sccoos_evidence',
    'staging_secoora_evidence'
  ]
  loop
    execute format(
      'create table if not exists public.%I (like public.staged_evidence including all)',
      table_name
    );
    execute format(
      'drop trigger if exists %I on public.%I',
      'set_' || table_name || '_updated_at',
      table_name
    );
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
      'set_' || table_name || '_updated_at',
      table_name
    );
  end loop;
end $$;
